"""add_crm_tables

Revision ID: 025a08dcc789
Revises: a3f1b2c4d5e6
Create Date: 2026-04-11 16:35:14.411522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025a08dcc789'
down_revision: Union[str, None] = 'a3f1b2c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_email_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_opened', sa.Integer(), nullable=True),
    sa.Column('total_replied', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_email_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_email_campaigns_status'), ['status'], unique=False)

    op.create_table('crm_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('crm_contacts',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('funnel_stage', sa.String(), server_default='new', nullable=True),
    sa.Column('email_sent_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('email_opened_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('email_replied_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_email_opened_at', sa.DateTime(), nullable=True),
    sa.Column('tg_sent_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('wa_sent_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_tg_at', sa.DateTime(), nullable=True),
    sa.Column('last_wa_at', sa.DateTime(), nullable=True),
    sa.Column('contact_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('last_contact_channel', sa.String(), server_default='', nullable=True),
    sa.Column('first_contact_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('stop_automation', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_contacts_funnel_stage'), ['funnel_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_last_contact_at'), ['last_contact_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_stop_automation'), ['stop_automation'], unique=False)

    op.create_table('crm_email_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email_to', sa.String(), nullable=False),
    sa.Column('email_subject', sa.String(), nullable=True),
    sa.Column('template_name', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('bounced_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tracking_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_email_logs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_email_logs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_email_logs_tracking_id'), ['tracking_id'], unique=True)

    op.create_table('crm_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_tasks_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_tasks_status'), ['status'], unique=False)

    op.create_table('crm_touches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_touches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_touches_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_touches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_touches_company_id'))

    op.drop_table('crm_touches')
    with op.batch_alter_table('crm_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_crm_tasks_company_id'))

    op.drop_table('crm_tasks')
    with op.batch_alter_table('crm_email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_email_logs_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_crm_email_logs_company_id'))
        batch_op.drop_index(batch_op.f('ix_crm_email_logs_campaign_id'))

    op.drop_table('crm_email_logs')
    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_contacts_stop_automation'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_last_contact_at'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_funnel_stage'))

    op.drop_table('crm_contacts')
    op.drop_table('crm_templates')
    with op.batch_alter_table('crm_email_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_email_campaigns_status'))

    op.drop_table('crm_email_campaigns')
    # ### end Alembic commands ###
